version: "3"

services:
  app:              #name of service
      build:        #build file
        context: .  # directory to build from
      ports:
        - "8000:8000"
      volumes:
        - ./app:/app
      command: >
        sh -c "python manage.py 0.0.0.0:8000"